samples:
  - unique_id: SL005_EA_1
    id: SL005
    file: 010__20201112__SL005__EA_Blank__nosplit.mzML
    condition: control
    description: Extraction Blank
    replicate: 1
    species: na

  - unique_id: SL005_EA_2
    id: SL005
    file: 011__20201112__SL005__EA_Blank__nosplit.mzML
    condition: control
    description: Extraction Blank
    replicate: 2
    species: na

  - unique_id: SL005_MB_1
    id: SL005
    file: 012__20201112__SL005__MB1__nosplit.mzML
    condition: Control
    description: Media Blank
    replicate: 1
    species: na

  - unique_id: SL005_BHI_1
    id: SL005
    file: 013__20201112__SL005__BHI_C__nosplit.mzML
    condition: Control
    description: Brain Heart Infusion
    replicate: 1
    species: na

  - unique_id: SL005_EL_24hr
    id: SL005
    file: 014__20201112__SL005__EL_C_24hr__nosplit.mzML
    condition: Treatment
    description: Sample 24hr
    replicate: 1
    species: E. lenta

  - unique_id: SL005_EL_48hr
    id: SL005
    file: 015__20201112__SL005__EL_C_48hr__nosplit.mzML
    condition: Treatment
    description: Sample 48hr
    replicate: 1
    species: E. lenta

  - unique_id: SL005_EL_72hr
    id: SL005
    file: 016__20201112__SL005__EL_C_72hr__nosplit.mzML
    condition: Treatment
    description: Sample 72hr
    replicate: 1
    species: E. lenta

  - unique_id: SL005_MB_2
    id: SL005
    file: 017__20201112__SL005__MB2__nosplit.mzML
    condition: Control
    description: Media Blank
    replicate: 2
    species: na

  - unique_id: SL005_BHI_2
    id: SL005
    file: 018__20201112__SL005__BHI_C__nosplit.mzML
    condition: Control
    description: Brain Heart Infusion
    replicate: 2
    species: na

  - unique_id: SL005_EA_3
    id: SL005
    file: 019__20201112__SL005__EA_Blank__nosplit.mzML
    condition: control
    description: Extraction Blank
    replicate: 3
    species: na