samples:
  - unique_id: SL2031_MB_1
    id: SL2031
    file: 003_20230825_SL2031__MB_MS1_neg.mzML
    condition: Control
    description: Method Blank
    replicate: 1
    species: n/a

  - unique_id: SL2031_MB_2
    id: SL2031
    file: 004_20230825_SL2031__MB_MS2_neg.mzML
    condition: Control
    description: Method Blank
    replicate: 2
    species: n/a

  - unique_id: SL2031_EL_cat1
    id: SL2031
    file: 018_20230825_SL2031__EL-cat_MS1_neg.mzML
    condition: Treatment
    description: Sample
    replicate: 1
    species: E. lenta

  - unique_id: SL2031_EL_cat2
    id: SL02031
    file: 019_20230825_SL2031__EL-cat_MS2_neg.mzML
    condition: Treatment
    description: Sample
    replicate: 2
    species: E. lenta